name: Gradle CI

on:
  push:
    branches: [ master, embedded ]
  pull_request:
    branches: [ master, embedded ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repository

    - name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build project
      run: |
        gradle wrapper
        bash gradlew shadow
    
    - name: Upload articact
      uses: actions/upload-artifact@v2
      with:
        path: build/libs
